import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from 'App/Models/User'
import Hash from '@ioc:Adonis/Core/Hash'

export default class UserSeeder extends BaseSeeder {
  public async run() {
    await User.createMany([
      {
        firstname: 'Avotra',
        lastname: 'Rakoto',
        email: 'avotra.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1, // Informatique
        jobTitleId: 1, // Développeur
        matricule: 'IT-INF-001', // Département Informatique (INF), 1er employé
        status: 'active',
      },
      {
        firstname: 'Bema',
        lastname: 'Andry',
        email: 'bema.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1, // Informatique
        jobTitleId: 2, // Administrateur Réseau
        matricule: 'IT-INF-002', // Département Informatique (INF), 2e employé
        status: 'active',
      },
      {
        firstname: 'Tiana',
        lastname: 'Rakoto',
        email: 'tiana.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2, // Ressources Humaines
        jobTitleId: 3, // Comptable
        matricule: 'RH-RES-001', // Département RH (RES), 1er employé
        status: 'active',
      },
      {
        firstname: 'Micka',
        lastname: 'Randria',
        email: 'micka.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2, // Ressources Humaines
        jobTitleId: 4, // Responsable RH
        matricule: 'RH-RES-002', // Département RH (RES), 2e employé
        status: 'active',
      },
      // --- MOCK TOP PERFORMERS ---
      {
        firstname: 'Alice',
        lastname: 'Rasoa',
        email: 'alice.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2, // RH
        jobTitleId: 3,
        matricule: 'RH-RES-003',
        status: 'active',
      },
      {
        firstname: 'Tiana',
        lastname: 'Rabekoto',
        email: 'rabekoto.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1, // Informatique
        jobTitleId: 1,
        matricule: 'IT-INF-003',
        status: 'active',
      },
      {
        firstname: 'Rado',
        lastname: 'Andry',
        email: 'rado.a@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5, // Commercial
        jobTitleId: 5,
        matricule: 'CM-COM-001',
        status: 'active',
      },
      //autres utilisateurs 35...
      {
        firstname: 'Sarah',
        lastname: 'Raveloson',
        email: 'sarah.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 5,
        matricule: 'FN-FIN-001',
        status: 'active',
      },
      {
        firstname: 'Jonas',
        lastname: 'Ramanantsoa',
        email: 'jonas.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 6,
        matricule: 'FN-FIN-002',
        status: 'active',
      },
      {
        firstname: 'Laura',
        lastname: 'Rasolo',
        email: 'laura.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 7,
        matricule: 'LG-LOG-001',
        status: 'active',
      },
      {
        firstname: 'Kevin',
        lastname: 'Rakotondrabe',
        email: 'kevin.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 8,
        matricule: 'LG-LOG-002',
        status: 'active',
      },
      {
        firstname: 'Noro',
        lastname: 'Andriamisa',
        email: 'noro.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 9,
        matricule: 'CM-COM-002',
        status: 'active',
      },
      {
        firstname: 'Luc',
        lastname: 'Rakotobe',
        email: 'luc.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 10,
        matricule: 'CM-COM-003',
        status: 'active',
      },
      {
        firstname: 'Aina',
        lastname: 'Ramaniraka',
        email: 'aina.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 7,
        matricule: 'LG-LOG-003',
        status: 'active',
      },
      {
        firstname: 'Jean',
        lastname: 'Rasolofo',
        email: 'jean.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 8,
        matricule: 'LG-LOG-004',
        status: 'active',
      },
      {
        firstname: 'Miora',
        lastname: 'Randriamanga',
        email: 'miora.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 3,
        matricule: 'RH-RES-004',
        status: 'active',
      },
      {
        firstname: 'Patrick',
        lastname: 'Ravelomanana',
        email: 'patrick.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 4,
        matricule: 'RH-RES-005',
        status: 'active',
      },
      {
        firstname: 'Cynthia',
        lastname: 'Rasambatra',
        email: 'cynthia.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 3,
        matricule: 'RH-RES-006',
        status: 'active',
      },
      {
        firstname: 'Eddy',
        lastname: 'Randrianasolo',
        email: 'eddy.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 4,
        matricule: 'RH-RES-007',
        status: 'active',
      },
      {
        firstname: 'Vanessa',
        lastname: 'Rasoanaivo',
        email: 'vanessa.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 5,
        matricule: 'FN-FIN-003',
        status: 'active',
      },
      {
        firstname: 'Eric',
        lastname: 'Rakotomanga',
        email: 'eric.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 6,
        matricule: 'FN-FIN-004',
        status: 'active',
      },
      {
        firstname: 'Naomi',
        lastname: 'Razanakoto',
        email: 'naomi.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 1,
        matricule: 'IT-INF-004',
        status: 'active',
      },
      {
        firstname: 'Julien',
        lastname: 'Ravelojaona',
        email: 'julien.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 2,
        matricule: 'IT-INF-005',
        status: 'active',
      },
      {
        firstname: 'Malala',
        lastname: 'Randriamanana',
        email: 'malala.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 3,
        matricule: 'RH-RES-008',
        status: 'active',
      },
      {
        firstname: 'Hery',
        lastname: 'Rakotondravoavy',
        email: 'hery.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 4,
        matricule: 'RH-RES-009',
        status: 'active',
      },
      {
        firstname: 'Elisa',
        lastname: 'Rasendrahmanana',
        email: 'elisa.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 5,
        matricule: 'FN-FIN-005',
        status: 'active',
      },
      {
        firstname: 'Samuel',
        lastname: 'Ratsimbazafy',
        email: 'samuel.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 6,
        matricule: 'FN-FIN-006',
        status: 'active',
      },
      {
        firstname: 'Tovo',
        lastname: 'Randrianarivony',
        email: 'tovo.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 7,
        matricule: 'LG-LOG-005',
        status: 'active',
      },
      {
        firstname: 'Olivia',
        lastname: 'Rasoarimanana',
        email: 'olivia.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 8,
        matricule: 'LG-LOG-006',
        status: 'active',
      },
      {
        firstname: 'Christian',
        lastname: 'Rakotovao',
        email: 'christian.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 9,
        matricule: 'CM-COM-004',
        status: 'active',
      },
      {
        firstname: 'Tina',
        lastname: 'Randrianantenaina',
        email: 'tina.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 10,
        matricule: 'CM-COM-005',
        status: 'active',
      },
      {
        firstname: 'Manitra',
        lastname: 'Rasolonirina',
        email: 'manitra.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 7,
        matricule: 'LG-LOG-007',
        status: 'active',
      },
      {
        firstname: 'Patrick',
        lastname: 'Rakotomalala',
        email: 'patrick2.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 4,
        jobTitleId: 8,
        matricule: 'LG-LOG-008',
        status: 'active',
      },
      {
        firstname: 'Sitraka',
        lastname: 'Raveloson',
        email: 'sitraka.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 3,
        matricule: 'RH-RES-010',
        status: 'active',
      },
      {
        firstname: 'Lova',
        lastname: 'Randriamisa',
        email: 'lova.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 2,
        jobTitleId: 4,
        matricule: 'RH-RES-011',
        status: 'active',
      },
      {
        firstname: 'Kanto',
        lastname: 'Rasolo',
        email: 'kanto.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 9,
        matricule: 'CM-COM-006',
        status: 'active',
      },
      {
        firstname: 'Tojo',
        lastname: 'Razanamanga',
        email: 'tojo.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 10,
        matricule: 'CM-COM-007',
        status: 'active',
      },
      {
        firstname: 'Harena',
        lastname: 'Rasanjy',
        email: 'harena.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 5,
        matricule: 'FN-FIN-007',
        status: 'active',
      },
      {
        firstname: 'Tahina',
        lastname: 'Rakotoarisoa',
        email: 'tahina.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 3,
        jobTitleId: 6,
        matricule: 'FN-FIN-008',
        status: 'active',
      },
      {
        firstname: 'Rindra',
        lastname: 'Ravoninahitriniarivo',
        email: 'rindra.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 1,
        matricule: 'IT-INF-006',
        status: 'active',
      },
      {
        firstname: 'Feno',
        lastname: 'Randrianina',
        email: 'feno.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 2,
        matricule: 'IT-INF-007',
        status: 'active',
      },
      {
        firstname: 'Yann',
        lastname: 'Rasoavelo',
        email: 'yann.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 1,
        matricule: 'IT-INF-008',
        status: 'active',
      },
      {
        firstname: 'Mialy',
        lastname: 'Randriambololona',
        email: 'mialy.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 1,
        jobTitleId: 2,
        matricule: 'IT-INF-009',
        status: 'active',
      },
      {
        firstname: 'Joel',
        lastname: 'Rakoto',
        email: 'joel.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 9,
        matricule: 'CM-COM-008',
        status: 'active',
      },
      {
        firstname: 'Nantenaina',
        lastname: 'Rasolonjatovo',
        email: 'nantenaina.r@generis.mg',
        password: await Hash.make('password'),
        departmentId: 5,
        jobTitleId: 10,
        matricule: 'CM-COM-009',
        status: 'active',
      }
    ])
  }
}
